
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication10;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ACCOUNT_LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ACCOUNT_LOGIN() {
   
          initComponents();
     first.setBackground(new Color(0,0,0,200));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        first = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(842, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        first.setBackground(new java.awt.Color(0, 0, 0));
        first.setMinimumSize(new java.awt.Dimension(842, 550));
        first.setPreferredSize(new java.awt.Dimension(842, 550));
        first.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setText("USERNAME");
        first.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 150, 30));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 51, 51));
        jTextField1.setText("xyz or 1=1");
        jTextField1.setToolTipText("ENTER USERNAME");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        first.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 270, 30));
        first.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 380, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 153, 255));
        jLabel2.setText("PASSWORD");
        first.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 150, 30));
        first.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 380, 10));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/Alogin.png"))); // NOI18N
        jButton1.setMnemonic('L');
        jButton1.setText("LOGIN");
        jButton1.setToolTipText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        first.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 270, -1));

        jPasswordField1.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 51, 51));
        jPasswordField1.setText("xyz or 1=1");
        jPasswordField1.setToolTipText("ENTER PASSWORD");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        first.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 270, 30));
        first.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, -1, -1));
        first.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        first.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 190, 20));
        first.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, -1, -1));
        first.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, -1, -1));
        first.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/hh.png"))); // NOI18N
        first.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 70, 70));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/gg.png"))); // NOI18N
        first.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 30, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/Facebook.png"))); // NOI18N
        first.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 30, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/Google-Plus.png"))); // NOI18N
        first.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 30, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/AInstagram.png"))); // NOI18N
        jLabel15.setMaximumSize(new java.awt.Dimension(842, 550));
        jLabel15.setMinimumSize(new java.awt.Dimension(842, 550));
        jLabel15.setPreferredSize(new java.awt.Dimension(842, 550));
        first.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 30, 30));

        getContentPane().add(first, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/BBBBBB.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 840, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String user = jTextField1.getText();
         String pass = jPasswordField1.getText();
         Options o = new Options();
        if(user.equalsIgnoreCase("shubham") && pass.equals("chauhan"))
        {
             this.setVisible(false);
             o.setVisible(true);
    
        }
       else
       {   
        jTextField1.setText("");
        jPasswordField1.setText("");
        jTextField1.requestFocus();
      jLabel8.setText("WARNING : ENTER CAREFULLY");
        JOptionPane.showMessageDialog(this,"INCORRECT USERNAME AND PASSWORD","ERROR",JOptionPane.ERROR_MESSAGE);

       }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
           int a= evt.getKeyCode();
           if(a == KeyEvent.VK_ENTER)
            jPasswordField1.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
           int a= evt.getKeyCode();
           if(a == KeyEvent.VK_ENTER)
            jButton1.requestFocus();
             // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
          String user = jTextField1.getText();
         String pass = jPasswordField1.getText();
         Options o = new Options();
         int a= evt.getKeyCode();
          if(a == KeyEvent.VK_ENTER)
     {      
     
        if(user.equalsIgnoreCase("shubham") && pass.equals("chauhan"))
        {
             this.setVisible(false);
             o.setVisible(true);
    
        }
       else
       {  
           
        jTextField1.setText("");
        jPasswordField1.setText("");
        jTextField1.requestFocus();
        JOptionPane.showMessageDialog(this,"INCORRECT USERNAME AND PASSWORD","ERROR",JOptionPane.ERROR_MESSAGE);
        jLabel8.setText("WARNING : ENTER CAREFULLY");
       }        // TODO add your handling code here:
     }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ACCOUNT_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
      //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ACCOUNT_LOGIN().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel first;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
